TESTING - Bfa priest mod
simulationcraft/simc pull request #4944
Opened 2019-09-10 23:16 UTC by kendrick-walls-work

PR - triggering CI testing
THIS PR IS BLOCKED BY PR simulationcraft/simc#4942

2019-09-10 23:26 UTC, kendrick-walls-work commented
build #11613.2 errored - see https://travis-ci.org/simulationcraft/simc/jobs/583411667 - CI started but did not complete run or fail tests (unran tests are not a fail but an error)

2019-09-11 21:50 UTC, kendrick-walls-work commented
ℹ️ retesting with recent changes from upstream

2019-09-11 22:45 UTC, kendrick-walls-work commented
✅ Ready for merge
ℹ️ should merge PR SimulationCraft#4949 first to avoid conflict across forks

2019-09-12 20:01 UTC, kendrick-walls-work commented
ℹ️ Build Job #11626.4 ended in error. THIS IS NOT A FAIL. (tests were not run due to error)

2019-09-12 22:38 UTC, seanpeters86 requested changes
Simc does not support these spells. Don’t add spells that aren’t implemented in the module. 

Simc should be kept dps focused until further support is added.

2019-09-12 22:39 UTC, seanpeters86 commented
Please use separate PRs for different specs. Also prefixing all commits with the class name in parentheses is the common standard. Look at other commits for reference.

2019-09-12 22:59 UTC, kendrick-walls-work commented
> Please use separate PRs for different specs. Also prefixing all commits with the class name in parentheses is the common standard. Look at other commits for reference.

commit https://github.com/simulationcraft/simc/pull/4944/commits/4057e6a1365379d5ee6088328df679d35640150c accomplishes this

2019-09-17 23:25 UTC, kendrick-walls-work commented
ℹ️ Unable to identify unimplemented spells I have resorted to testing via raidbots' nightly build, with config file custom APL.
- any specific details on the healing spells you, @seanpeters86, believe are unimplemented in this APL would be helpful in implementing the changes requested.

2019-09-19 22:50 UTC, kendrick-walls-work commented
ℹ️ Proof healing spell sim is implemented for priest to some degree: https://www.raidbots.com/simbot/report/8Uqvn2M5RsH1vMseiM2dR8/simc
Note the HPS data is present!

2019-09-19 23:21 UTC, kendrick-walls-work commented
I have generated a test profile for the current state of holy priests and like *every* other class could be improved but it provides a starting point for priest healers to use.
example use:
https://www.raidbots.com/simbot/report/3tW3tQ7yXZT1pejtGikb9c/simc

```
priest="Åmåk"
source=blizzard
origin="https://worldofwarcraft.com/en-us/character/malfurion/%C3%A5m%C3%A5k"
thumbnail="https://render-us.worldofwarcraft.com/character/malfurion/205/153908173-inset.jpg"
spec=holy
level=120
race=human
role=heal
position=back
talents=https://worldofwarcraft.com/en-us/game/talent-calculator#priest/holy/talents=2313333
azerite_essences=20:3:1/27:1:0

# Default consumables
potion=battle_potion_of_intellect
flask=greater_flask_of_endless_fathoms
food=baked_port_tato
augmentation=battle_scarred

# Executed before combat begins. Accepts non-harmful actions only.

# Executed every time the actor is available.
actions=mana_potion,if=mana.pct<=50
actions+=/renew,cycle_targets=1,max_cycle_targets=15,if=!ticking&target.health.pct<=99&mana.pct>20&target.health.pct>0
actions+=/renew,cycle_targets=1,max_cycle_targets=15,if=!ticking&target.health.pct<=80&target.health.pct>0
actions+=/flash_heal,if=target.health.pct>0&target.health.pct<50&cooldown.holy_word_serenity.remains>=0.2,cycle_targets=1,max_cycle_targets=5
actions+=/holy_word_serenity,if=target.health.pct>0&target.health.pct<50,cycle_targets=1,max_cycle_targets=5
actions+=/heal,if=target.health.pct>49&target.health.pct<98,cycle_targets=1
actions+=/stop_moving,if=self.mana.pct>14&cooldown.holy_word_serenity.remains>=0.3
actions+=/start_moving,if=self.mana.pct<=5
actions+=/holy_fire,if=mana.pct>20
actions+=/smite,if=mana.pct>19

head=grasping_crown_of_the_deep,id=159252,bonus_id=5448/1617/4786/6270,azerite_powers=0/15/18/228/165
neck=heart_of_azeroth,id=158075,bonus_id=4932/4933/6316,azerite_level=62
shoulders=fathomfeeders_mantle,id=168342,bonus_id=4822/1487/4786/6265/4775,azerite_powers=13/15/103/576/114
back=sporecallers_shroud,id=159292,bonus_id=5010/1612/4783
chest=vestments_of_creeping_terror,id=168337,bonus_id=4823/1502/4786/6266/4775,azerite_powers=13/15/103/228/114
shirt=artisan_officers_shirt,id=89195
tabard=renowned_guild_tabard,id=69210
wrists=silk_cuffs_of_the_skycapn,id=159227,bonus_id=5010/1612/4783
hands=handwraps_of_oscillating_polarity,id=159247,bonus_id=5010/43/1602/4786
waist=redhooks_cummerbund,id=159965,bonus_id=5010/4802/1602/4786,gems=80int
legs=downlined_breeches,id=159234,bonus_id=5010/1602/5860/4784
feet=blood_warders_moccasins,id=159270,bonus_id=5010/1612/4783
finger1=band_of_the_ancient_dredger,id=159461,bonus_id=5010/1612/5850/4784,enchant=60haste
finger2=band_of_the_roving_scalawag,id=162541,bonus_id=5008/1587/5860/4784,enchant=60haste
trinket1=zoatroid_egg_sac,id=169309,bonus_id=4799/1502/4786
trinket2=luminous_jellyweed,id=169312,bonus_id=4799/1502/4786
main_hand=g3t00t,id=159641,bonus_id=5010/4802/41/1602/5850/4783,gems=120int,enchant=oceanic_restoration
off_hand=tidebinders_driftglobe,id=168477,bonus_id=4799/1502/4786

# Gear Summary
# gear_ilvl=436.38
# gear_stamina=13336
# gear_intellect=8893
# gear_crit_rating=1342
# gear_haste_rating=888
# gear_mastery_rating=1145
# gear_versatility_rating=345
# gear_leech_rating=63
# gear_armor=1668
```

2019-10-05 02:03 UTC, seanpeters86 requested changes
This PR has inaccurate data in it that does not reflect how to actually play a holy priest in a raid or dungeon environment. Profile and APL work is the last thing that should be done when adding a new spec, let alone a healing APL. 

Adding this into the code base is going to mislead anyone that looks at it, especially if they attempt to use it. Glancing at several guides the content in this PR goes against everything I'm reading, and doesn't even begin to show how to play a Holy Priest for healing.

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.cpp
> +    ( primary_role() != ROLE_HEAL ) ? "potion_of_wild_mending" : /* id 300741 - healers */
I have yet to see a guide or parse use this potion, and this is not implemented.

Example: https://www.wowhead.com/holy-priest-enhancements-guide

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.cpp
> +    // as of at least 2019-09-01, but likly much earlyer
```suggestion
    // as of at least 2019-09-01, but likely much earlier
```

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest_holy.cpp
> +  precombat->add_action( this, "Renew" );
No guide I'm seeing has renew as a pre-combat action. What is the purpose of this?

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest_holy.cpp
> +  default_list->add_action( this, "Renew", "cycle_targets=1,max_cycle_targets=15,if=!ticking&target.health.pct<=99&mana.pct>20" );
This will just blanket renew the entire raid. This is not how you play a holy priest, you'll just run out of mana.

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest_holy.cpp
> +  default_list->add_action( this, "Renew", "cycle_targets=1,max_cycle_targets=15,if=!ticking&target.health.pct<=80" );
This will just blanket renew the entire raid. This is not how you play a holy priest, you'll just run out of mana.

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest_holy.cpp
> +  default_list->add_action( this, "Heal", "if=target.health.pct>49&target.health.pct<98,cycle_targets=1" );
where did you get these percents? Healing is much more dynamic than this...

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest_holy.cpp
> +  default_list->add_action( "start_moving", "if=self.mana.pct<=5" );
what is the point of this?

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest_holy.cpp
> +  default_list->add_action( "stop_moving", "if=self.mana.pct>14&cooldown.holy_word_serenity.remains>=0.3" );
what is the point of this?

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest_holy.cpp
> +  // offence to reduce incoming damage APL
why is this in the same apl? shouldnt this be in a separate one for damage?

2019-10-05 02:03 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest_holy.cpp
> +  default_list->add_action( this, "Holy Fire" );
this will never execute, smite will always be available

2019-10-05 02:03 UTC, seanpeters86 commented on profiles/DS_Dungeon.simc
> +DS_Priest_Holy.simc
this should not be added until everything is done

2019-10-05 02:03 UTC, seanpeters86 commented on profiles/DungeonSlice/DS_Priest_Holy.simc
> +priest="DS_Priest_Holy"
this should not be added until everything is done

2019-10-05 02:03 UTC, seanpeters86 commented on profiles/T23_Raid.simc
> +T23_Priest_Holy.simc
this should not be added until everything is done

2019-10-05 02:03 UTC, seanpeters86 commented on profiles/T24_Raid.simc
> +T24_Priest_Holy.simc
this should not be added until everything is done

2019-10-05 02:03 UTC, seanpeters86 commented on profiles/generators/DungeonSlice/DS_Generate_Priest.simc
> +priest="PR_Priest_Holy"
this should not be added until everything is done

2019-10-05 02:03 UTC, seanpeters86 commented on profiles/generators/Tier23/T23_Generate_Priest.simc
> +priest="T23_Priest_Holy"
this should not be added until everything is done

2019-10-05 02:03 UTC, seanpeters86 commented on profiles/generators/Tier24/T24_Generate_Priest.simc
> +priest="T24_Priest_Holy"
this should not be added until everything is done

2020-02-03 18:47 UTC, closed without merging