[Priest] Add Power Word: Shield insanity generation.
simulationcraft/simc pull request #5195
Opened 2020-08-05 17:13 UTC by djriff

This includes insanity generation from Hallucinations and Fae Blessings.

2020-08-05 17:18 UTC, seanpeters86 requested changes

2020-08-05 17:18 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.cpp
> +  gains.insanity_night_fae					   = get_gain( "Insanity Gained from Power Word: Shield with Fae Blessings." );
this name should be more descriptive

2020-08-05 17:18 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.hpp
> +	propagate_const<gain_t*> insanity_night_fae;
fix indents

2020-08-05 17:18 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.cpp
> +  gains.insanity_night_fae					   = get_gain( "Insanity Gained from Power Word: Shield with Fae Blessings." );
fix indents

2020-08-05 17:18 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.cpp
> +	};
this entire section is indented too much, and you are using too large of a gap with your tabbed lines (see above)

Also make sure when you use a paren you have proper spacing. `priest().genereate_insanity( x )`

2020-08-05 17:19 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.cpp
> +
extra line here

2020-08-06 01:27 UTC, seanpeters86 requested changes

2020-08-06 01:27 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.hpp
> +	  propagate_const<gain_t*> insanity_power_word_shield_hallucinations;
indent is wrong

2020-08-06 01:27 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.cpp
> +  gains.insanity_ascended_blast                = get_gain( "Insanity Gained from Ascended Blast" );
idk why this is added, probably a bad merge

2020-08-06 01:27 UTC, seanpeters86 commented on engine/class_modules/priest/sc_priest.cpp
> +    if (priest().specialization() == PRIEST_SHADOW)
this is wrong spacing 

```suggestion
    if ( priest().specialization() == PRIEST_SHADOW )
```

2020-08-06 06:32 UTC, scamille commented
The main problem is that you use tabs instead of spaces, see https://github.com/simulationcraft/simc/wiki/CodingGuidelines

But I would recommend that for the priest source code you just run clang-format on the files, and it does everything automatically for you. Most modern IDEs have a way of integrating clang-format, and then it is just one click to format the file you are currently working on.

2020-08-08 02:39 UTC, djriff commented
I'm not sure what is happening with the tabs vs spaces. I manually spaced everything out so it conformed with the standards before I pushed anything.

> The main problem is that you use tabs instead of spaces, see https://github.com/simulationcraft/simc/wiki/CodingGuidelines
> 
> But I would recommend that for the priest source code you just run clang-format on the files, and it does everything automatically for you. Most modern IDEs have a way of integrating clang-format, and then it is just one click to format the file you are currently working on.

Clang was refusing to work in VS for me for some reason, which is the only reason I resorted to manually spacing it out.

2020-08-13 20:12 UTC, seanpeters86 commented
Fae Blessings has been changed, we no longer need this

2020-08-13 20:12 UTC, closed without merging