Shadowflame prism
simulationcraft/simc pull request #5269
Opened 2020-09-13 18:55 UTC by seanpeters86

2020-09-13 19:08 UTC, scamille requested changes

2020-09-13 19:08 UTC, scamille commented on engine/class_modules/priest/sc_priest.cpp
> +void priest_t::trigger_shadowflame_prism( player_t* target )
Some things which should probably still be improved here:
1. Check if current_pet is nullptr or not. Either add an assert, or if it is possible to trigger shadowflame prism without having a main pet (eg. no summon lines in the APL) just return without doing anything.

2. Move the assert current_pet->shadowflame_prism inside the !sleeping condition.

3. Why did you remove the set_target line? I would assume it works again after your other fixes.

2020-09-13 19:08 UTC, scamille commented on engine/class_modules/priest/sc_priest.hpp
> +  double duration;
please use timespan_t here. That way the units are handled at the point of initialization and not during usage of the value.

2020-09-13 19:08 UTC, scamille commented on engine/class_modules/priest/sc_priest.hpp
> +    auto current_pet = p().o().talents.mindbender->ok() ? p().o().pets.mindbender : p().o().pets.shadowfiend;
You should be able to use the get_current_main_pet() function here. Also check if the current_pet variable you retrieve is null or not.

2020-09-14 00:54 UTC, lgkern approved these changes

2020-09-14 01:03 UTC, merged