[Warlock] Implement Impending Catastrophe
simulationcraft/simc pull request #5358
Opened 2020-10-02 04:22 UTC by javedbartlett

2020-10-02 05:52 UTC, scamille commented
Does this really require a ground aoe event?

I am no warlock and have only read the spell description - but would it be possible to do like this:
- the main action is a normal simple action and you use impact_action variable to trigger the custom code there.
- set the impact to aoe
- let the impact action trigger the dot in its impact function as a single target dot. (Will be triggered for all targets hit be the impact action)

2020-10-02 06:05 UTC, Azevara commented
Since we don't do any real things to handle damage done "in flight" this is being treated as doing that in flight damage right at the impact time.

The ground aoe event is unnecessary and can probably be scrapped in favor of just triggering the dot after the in flight damage trigger.

2020-10-02 07:25 UTC, Azevara requested changes

2020-10-02 07:25 UTC, Azevara commented on engine/class_modules/warlock/sc_warlock.cpp
> +
As mentioned in the comments on this PR, the event code should be changed into something that triggers the action directly on each target, either through aoe or as part of the cycle through the target list that occurs for the inflight damage

2020-10-08 11:40 UTC, nuoHep commented on engine/class_modules/warlock/sc_warlock.cpp
> +    dot_duration *= 1 + p->conduit.catastrophic_origin.percent();
Dunno if it works like that, but the conduit reads
  `Impending Catastrophe's damage over time and the inflicted Curse last |cFFFFFFFF${$s1}.1%|r longer against your primary target.`
If it actually does work like that, you'll have to change this so the dot duration isn't extended for all targets hit.

Pretty sure what you could do is to override `action_t::composite_dot_duration()` with smth like
```cpp
timespan_t composite_dot_duration( const action_state_t* s ) const override
{
  if ( s->chain_target = 0 ) // main target
    return dot_duration * ( 1 + p->conduit.catastrophic_origin.percent() );
  return dot_duration;
}
```

2020-10-22 08:11 UTC, merged