[Death Knight] Epidemic fixes
simulationcraft/simc pull request #5478
Opened 2020-10-31 00:16 UTC by Ceriloch

### Target cap Issue

Epidemic is capped at 20 targets, with the secondary eruption capped at 6 targets.  Spell data for the main spell, 207317, shows 20 max targets, and spell data for the child spell(s) both show 7 targets.  A change in SL shows that the first child spell, 212739, had a secondary spell effect added to it, that has matching coefficient with the other child spell, 215969.  Main spell still refers to both of them in the tool tip.  Testing has shown that the splash damage only hits 6 targets.

109 casts * 20 = 2180 main target hits
2180 main target hits * 6 = 13080 secondary splash hits
2180 main target hits * 7 = 15260 secondary splash hits

### Damage Issue

Epidemic was also using the wrong coefficient for epidemic_main.  a_mod was being set to 0.08 for both main, and aoe.  It should be 0.20 for main, and 0.08 for aoe.  In 212739 since it has both coefficients in it, it looks like it was using effect 2 coefficient, which is 0.08 instead of reading it from effect 1 which has 0.20.

#### Profile
```
./simc ../profiles/Tier25/T25_Death_Knight_Unholy.simc enemy=t1 enemy=t2 enemy=t3 enemy=4 enemy=5 enemy=6 enemy=7 enemy=8 enemy=9 enemy=10 enemy=11 enemy=12 enemy=13 enemy=14 enemy=15 enemy=16 enemy=17 enemy=18 enemy=19 enemy=20 enemy=21 enemy=22 enemy=23 enemy=24 enemy=25 enemy=26 enemy=27 enemy=28 enemy=29 enemy=30
```

#### Test Results
```
Original

    epidemic                   Count= 109.0|  2.698sec  DPE=126044| 0.00%  DPET=136432  DPR= 5493  pDPS=    0
    epidemic_aoe               Count=15258.3|  2.698sec  DPE=   600|44.10%  DPET=     0  DPR=    0  pDPS=30546  Miss= 0.00%  Hit=   222|   132|   395  Crit=   446|   264|   789|34.84%
    epidemic_main              Count=2179.8|  2.698sec  DPE=  2101|22.05%  DPET=     0  DPR=    0  pDPS=15272  Miss= 0.00%  Hit=   222|   132|   395  Crit=   446|   264|   789|34.83%

Post Fix
    epidemic                   Count= 108.6|  2.700sec  DPE=126129| 0.00%  DPET=136521  DPR= 5496  pDPS=    0
    epidemic_aoe               Count=13030.8|  2.700sec  DPE=   300|18.89%  DPET=     0  DPR=    0  pDPS=13107  Miss= 0.00%  Hit=   222|   132|   395  Crit=   446|   264|   791|34.84%
    epidemic_main              Count=2171.8|  2.700sec  DPE=  4505|47.23%  DPET=     0  DPR=    0  pDPS=32767  Miss= 0.00%  Hit=   556|   330|   988  Crit=  1116|   659|  1977|34.83%
```

2020-10-31 00:59 UTC, Ceriloch commented
Hold on merge for now.  I'm going to test epidemic splash targets in SL tonight, as there has been some conflicting information lately on what the cap actually is.

2020-11-01 05:33 UTC, Ceriloch commented
Tested it on multiple sizes of packs from 6 - 15.

It is a total of 7 targets.  main target + 6 splash targets.  Implementation as coded in this pull request should be correct.

12 target epidemic - 6 hit by splash
![image](https://user-images.githubusercontent.com/3732166/97795834-809b4280-1bc8-11eb-9659-b0903d16c59b.png)

9 target epidemic - 6 hit by splash
![image](https://user-images.githubusercontent.com/3732166/97795879-eee00500-1bc8-11eb-9548-3c69e658292d.png)


6 target epidemic - 5 hit by splash
![image](https://user-images.githubusercontent.com/3732166/97795850-b3ddd180-1bc8-11eb-8583-b4bb6e313af7.png)

2020-11-02 05:54 UTC, Ceriloch commented
Hastily hacked together test harness to test target scaling

```
#!/usr/bin/env python3

import os
import json
import subprocess
import unittest

base_path = os.path.join("/home/ceriloch/code/")
path_to_simc = os.path.join(base_path, 'ceriloch-simc', 'engine', 'simc')

class TestDeathKnightUnholy(unittest.TestCase):
    profile = os.path.join(base_path, 'ceriloch-simc', 'profiles', 'Tier25', 'T25_Death_Knight_Unholy.simc')

    def _epidemic(self, num_targets):
        cmd = [path_to_simc]
        for x in range(num_targets):
            cmd.append(f'enemy={x}')
        cmd.extend(['json=test.json', self.profile])
        subprocess.check_call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        with open('test.json', 'r') as f:
            json_doc = json.load(f)
            for entry in json_doc['sim']['players'][0]['stats']:
                if 'epidemic' in entry['name']:
                    num_executes = entry['num_executes']['mean']
                    for child in entry['children']:
                        if child['name'] == 'epidemic_main':
                            main_num_executes = child['num_executes']['mean']
                        elif child['name'] == 'epidemic_aoe':
                            splash_num_executes = child['num_executes']['mean']

        expected_epidemic_main = num_executes * min(num_targets, 20)
        
        splash_targets = min(num_targets - 1, 6)
        expected_splash_executes = splash_targets * expected_epidemic_main

        self.assertAlmostEqual(expected_epidemic_main,  main_num_executes, delta=1)
        self.assertAlmostEqual(expected_splash_executes, splash_num_executes, delta=1)
        print(f"Targets: {num_targets:4}\tCasts: {num_executes:10.3f}\tMain: {main_num_executes:10.3f}\tSplash: {splash_num_executes:10.3f}")

    def test_epidemic_targets(self):
        for x in range(2, 30):
            self._epidemic(x)

if __name__ == '__main__':
    unittest.main()
```

#### Output
```
Targets:    2   Casts:    103.346       Main:    206.691        Splash:    206.691
Targets:    3   Casts:    105.660       Main:    316.981        Splash:    633.963
Targets:    4   Casts:    107.491       Main:    429.963        Splash:   1289.888
Targets:    5   Casts:    108.617       Main:    543.085        Splash:   2172.339
Targets:    6   Casts:    108.781       Main:    652.685        Splash:   3263.427
Targets:    7   Casts:    108.883       Main:    762.177        Splash:   4573.064
Targets:    8   Casts:    108.802       Main:    870.410        Splash:   5222.462
Targets:    9   Casts:    108.466       Main:    976.190        Splash:   5857.141
Targets:   10   Casts:    108.594       Main:   1085.922        Splash:   6515.531
Targets:   11   Casts:    108.841       Main:   1197.249        Splash:   7183.496
Targets:   12   Casts:    108.637       Main:   1303.635        Splash:   7821.807
Targets:   13   Casts:    108.721       Main:   1413.361        Splash:   8480.163
Targets:   14   Casts:    109.100       Main:   1527.397        Splash:   9164.383
Targets:   15   Casts:    108.437       Main:   1626.561        Splash:   9759.364
Targets:   16   Casts:    108.601       Main:   1737.620        Splash:  10425.723
Targets:   17   Casts:    108.850       Main:   1850.426        Splash:  11102.554
Targets:   18   Casts:    108.757       Main:   1957.627        Splash:  11745.762
Targets:   19   Casts:    108.348       Main:   2058.600        Splash:  12351.599
Targets:   20   Casts:    108.323       Main:   2166.463        Splash:  12998.779
Targets:   21   Casts:    108.569       Main:   2171.380        Splash:  13028.279
Targets:   22   Casts:    109.024       Main:   2180.474        Splash:  13082.845
Targets:   23   Casts:    108.893       Main:   2177.856        Splash:  13067.139
Targets:   24   Casts:    108.735       Main:   2174.706        Splash:  13048.236
Targets:   25   Casts:    108.852       Main:   2177.046        Splash:  13062.278
Targets:   26   Casts:    108.319       Main:   2166.381        Splash:  12998.288
Targets:   27   Casts:    108.577       Main:   2171.519        Splash:  13029.113
Targets:   28   Casts:    109.038       Main:   2180.744        Splash:  13084.463
Targets:   29   Casts:    108.577       Main:   2171.541        Splash:  13029.248
.
----------------------------------------------------------------------
Ran 1 test in 249.257s

OK
```

2020-11-02 12:59 UTC, Melekus commented on engine/class_modules/sc_death_knight.cpp
>      aoe = aoe - 1;
This main damage component should be set to 0, because it is single target.

2020-11-02 13:02 UTC, Melekus commented on engine/class_modules/sc_death_knight.cpp
> +    aoe = 0;
The secondary damage component's aoe should be set to aoe - 1 (or data().max_targets() - 1) and not 0.
The way the spell works is that every flare up on enemies generate a secondary aoe that doesn't hit the enemy that generates it (the "source").
With your current implementation, each flare up would deal damage to the source enemy as well as everything around it *with the higher spelldata coefficient* and then deal the smaller amount to a single target around the source.

2020-11-02 13:05 UTC, Melekus requested changes
This implementation doesn't reflect how epidemic works in the game.

2020-11-02 22:39 UTC, Melekus approved these changes

2020-11-03 00:58 UTC, merged