[Elemental] Apl
simulationcraft/simc pull request #5513
Opened 2020-11-12 16:55 UTC by HawkCorrigan

2020-11-12 19:12 UTC, Bloodmallet requested changes
There are quite a lot of APL lines that seem improvable.

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +        "primordial_wave,target_if=min:dot.flame_shock.remains,cycle_targets=1,if=!buff.primordial_wave.up" );
Does `min:dot.flame_shock.remains` actually pick up targets without Flame Shock?

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +        "target_if=refreshable&(spell_targets.chain_lightning<(5-!talent.totem_mastery.enabled)|!talent.storm_"
`totem_mastery` is long gone :eyes:

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +                     "if=runeforge.echoes_of_great_sundering.equipped&buff.echoes_of_great_sundering.up" );
No Master of Elements gaming with this buff?

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +    aoe->add_action( this, "Chain Lightning", "if=buff.stormkeeper.remains<3*gcd*buff.stormkeeper.stack",
This line has no effect, because the next line is Chain Lightning anyway

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +    aoe->add_action( this, "Lava Burst", "moving=1,if=talent.ascendance.enabled" );
should use `cooldown_react` instead of this talent ascendance condition

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +        "target_if=(!ticking|dot.flame_shock.remains<=gcd|talent.ascendance.enabled&dot.flame_shock.remains<(cooldown."
The whole ascendance condition block can be removed. Ascendance refreshes Flame Shock now

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +        "if=talent.stormkeeper.enabled&(raid_event.adds.count<3|raid_event.adds.in>50)&(maelstrom<44)" );
Why are you limiting MS to 43 in single target?

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> -    single_target->add_talent( this, "Static Discharge", "if=talent.static_discharge.enabled" );
Static Discharge is not re-added again

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> -    aoe->add_talent( this, "Echoing Shock", "if=talent.echoing_shock.enabled" );
Was the removal of Echoing Shock from AoE a deliberate choice?

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +        "if=(spell_targets.chain_lightning>1)&(!dot.flame_shock.refreshable|pet.storm_elemental.active)&(!talent."
What does this line have to do with Flame Shock?

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +    single_target->add_action( this, "Earthquake", "if=spell_targets.chain_lightning>1&!runeforge.echoes_of_great_sundering.equipped|(buff.echoes_of_great_sundering.up&buff.master_of_the_elements.up)
Will probably munch Maelstrom when playing Aftershock

2020-11-12 19:12 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +    single_target->add_action( this, "Chain Lightning", "if=!buff.stormkeeper.up&spell_targets.chain_lightning>1" );
Versus two targets casting Lightning Bolt looks like the better choice to me. 
![image](https://user-images.githubusercontent.com/9075987/98984983-377db380-2523-11eb-9571-6d16bbc6fc4b.png)

2020-11-12 21:53 UTC, merged

2020-11-13 07:49 UTC, navv1234 commented on engine/class_modules/sc_shaman.cpp
> +        "primordial_wave,target_if=min:dot.flame_shock.remains,cycle_targets=1,if=!buff.primordial_wave.up" );
`min` specifier on target if will cast on the target that has the minimum value of that expression, including targets that have the value "0". Using `cycle_targets` and `target_if` together is unspecified behavior, I at least don't know what happens then.