Add SpellID into gains/loses formats
simulationcraft/simc pull request #5770
Opened 2021-01-24 13:08 UTC by MichelPate

Add SpellID information for gains and loses outputs

2021-01-24 16:06 UTC, Melekus commented on engine/buff/sc_buff.cpp
> +        sim->print_log( "{} loses {} ({})", *player, buff_display_name, s_data->id() );
```suggestion
        sim->print_log( "{} loses {} ({})", *player, name_str, s_data->id() );
```
This should be name_str to mirror the display without log_spell_id

2021-01-25 16:42 UTC, scamille commented
It swould be easier to log just ```*this``` instead of ```name_str``` for the buff, and then you get the automatic output I put in place.

So just do:
```sim->print_log( "{} loses {}", *player, *this );```
should print 'Player xy loses Buff b' or 'Player xy loses Buff b (buff_id)'.

2021-01-26 19:19 UTC, scamille requested changes

2021-01-26 19:19 UTC, scamille commented on engine/buff/sc_buff.cpp
> +      }
```suggestion
      sim->print_log( "{} loses {}", *player, *this );
```

2021-01-26 19:19 UTC, scamille commented on engine/buff/sc_buff.cpp
> +        }
```suggestion
        std::string buff_display_name = fmt::format("{} (stacks={})", *this, current_stack );
        sim->print_log( "{} gains {} (value={})", *player, buff_display_name, current_value );
```

This requires changing line 2371 as well.

Should give a line like:
Player X gains Buff Y (spell_id) (current_stack=N) (value=x)

2021-01-27 21:11 UTC, scamille commented on engine/buff/sc_buff.cpp
> +      }
The idea was to replace the whole block with this.

formatting *this (the buff_t object) will automatically print either 'Buff X' or 'Buff X (id)'. So there is no need for the if statement here.

2021-01-27 21:20 UTC, merged