[Priest] first pass at t28 set bonuses
simulationcraft/simc pull request #6209
Opened 2021-11-19 03:43 UTC by seanpeters86

first pass at 2 and 4 set bonuses for shadow priest in t28

https://www.wowhead.com/news/datamined-priest-tier-set-bonuses-in-patch-9-2-discipline-holy-shadow-324965

2021-11-19 13:37 UTC, HawkCorrigan commented
sorry, I misclicked something

2021-11-20 09:49 UTC, scamille commented on engine/class_modules/priest/sc_priest_shadow.cpp
> +      if ( priest().pets.your_shadow.n_active_pets() < 1 )
You could simplify this check by just calling `auto pet = priest().pets.your_shadow.active_pet();` and then checking if pet is null or not.

2021-11-20 09:51 UTC, scamille commented on engine/class_modules/priest/sc_priest_shadow.cpp
> +    if ( priest().sets->has_set_bonus( PRIEST_SHADOW, T28, B4 ) )
This might be a micro-optimization, but you could store this in a boolean which is set in the constructor.

2021-11-20 09:52 UTC, scamille commented on engine/sc_enums.hpp
> +  T28
I know this is all temporary, but T28 should definitely go before SET_BONUS_MAX, otherwise various stuff will break.

2021-11-20 09:52 UTC, scamille approved these changes

2021-11-21 12:35 UTC, scamille requested changes
Change options_str type caused by merging #6208

2021-11-21 12:35 UTC, scamille commented on engine/class_modules/priest/sc_priest_pets.cpp
> +  action_t* create_action( util::string_view name, const std::string& options_str ) override;
```suggestion
  action_t* create_action( util::string_view name, util::string_view options_str ) override;
```

2021-11-21 12:36 UTC, scamille requested changes
Change options_str type caused by merging #6208

2021-11-21 12:36 UTC, scamille commented on engine/class_modules/priest/sc_priest_pets.cpp
> +action_t* your_shadow_t::create_action( util::string_view name, const std::string& options_str )
```suggestion
action_t* your_shadow_t::create_action( util::string_view name, util::string_view options_str )
```

2021-11-21 18:48 UTC, Saeldur approved these changes

2021-11-21 18:49 UTC, merged