[Paladin] First draft of prot T28 profile
simulationcraft/simc pull request #6342
Opened 2022-02-15 07:43 UTC by OrcinusDrake

Unsure of what to do with trinkets and whether pants or hands or the better off-set piece. Could also re-run sims for theotar vs nadja as I haven't checked that yet.

2022-02-16 10:16 UTC, OrcinusDrake commented
Using dungeon trinks as the raid ones aren't implemented in simc atm. Also they suck. So might change later if they get retuned.

2022-03-05 17:40 UTC, Melekus commented on profiles/generators/Tier28/T28_Generate_Paladin.simc
>  save=T27_Paladin_Protection.simc
Don't forget to update the file name to T28

2022-03-06 05:42 UTC, Armadk requested changes
bonus_id 6935 should be added for items with sockets

Current rules allow for a socket on head, neck, wrists, waist, and both rings.  So you may want to also include sockets for head, wrist, and waist.

2022-03-06 05:42 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Paladin.simc
> +neck=Worldkiller_Iris,id=189859,bonus_id=7187/1524,gem_id=173128
```suggestion
neck=Worldkiller_Iris,id=189859,bonus_id=6935/7187/1524,gem_id=173128
```

2022-03-06 05:42 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Paladin.simc
> +finger1=Rygelons_Heraldric_Ring,id=189854,bonus_id=7187/1524,enchant=tenet_of_haste,gem_id=173128
```suggestion
finger1=Rygelons_Heraldric_Ring,id=189854,bonus_id=6935/7187/1524,enchant=tenet_of_haste,gem_id=173128
```

2022-03-06 05:42 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Paladin.simc
> +finger2=Loquacious_Keepers_Peridot,id=189802,bonus_id=7187/1524,enchant=tenet_of_haste,gem_id=173128
```suggestion
finger2=Loquacious_Keepers_Peridot,id=189802,bonus_id=6935/7187/1524,enchant=tenet_of_haste,gem_id=173128
```

2022-03-06 05:42 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Paladin.simc
>  save=T27_Paladin_Protection.simc
```suggestion
save=T28_Paladin_Protection.simc
```

2022-03-06 06:55 UTC, OrcinusDrake commented
Okay implemented those suggestions, thank you. Based on newer information, upgraded the hands to 285 too.

2022-03-06 08:52 UTC, Armadk approved these changes

2022-03-07 06:42 UTC, merged