Protection Warrior T28 Profile
simulationcraft/simc pull request #6414
Opened 2022-02-25 17:03 UTC by Mwahi

2022-02-26 20:38 UTC, Azevara commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
>  # save=T27_Warrior_Protection.simc
File name requires updating here.

2022-03-06 05:48 UTC, Armadk requested changes

2022-03-06 05:48 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +main_hand=devastated_worldshard,id=189851,bonus_id=4800/4786/1524,enchant=sinful_revelation
```suggestion
main_hand=devastated_worldshard,id=189851,bonus_id=7187/1524,enchant=sinful_revelation
```

2022-03-06 05:48 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +off_hand=ruined_crest_of_lordaeron,id=189845,bonus_id=4800/4786/1524
```suggestion
off_hand=ruined_crest_of_lordaeron,id=189845,bonus_id=7187/1524
```

2022-03-12 11:11 UTC, Armadk approved these changes

2022-03-12 11:11 UTC, merged