Prot Warrior T28 Profile/APL
simulationcraft/simc pull request #6490
Opened 2022-03-23 16:14 UTC by Mwahi

Nomerature's T28 Profile/APL update
https://www.raidbots.com/simbot/report/8wSZcYWp6XiiV9fd3VU5Yt

2022-03-23 18:15 UTC, Armadk commented on engine/class_modules/sc_warrior.cpp
> +  generic -> add_action( this, "Shield Slam", "if=buff.shield_block.up||buff.outburst.up&rage<=55" );
```suggestion
  generic -> add_action( this, "Shield Slam", "if=buff.shield_block.up|buff.outburst.up&rage<=55" );
```

2022-03-24 11:45 UTC, nyterage reviewed
putting through one of these changes should fix the CI error

2022-03-24 11:45 UTC, nyterage commented on engine/class_modules/sc_warrior.cpp
> +  default_list -> add_action( this, "heroic_charge,if=rage<=40");
``
```suggestion
  default_list -> add_action( "heroic_charge,if=rage<=40" );
```

or 

```suggestion
  default_list -> add_action( this, "Heroic Charge", "if=rage<=40" );
```

current line is causing it to error out looking for an ability called "heroic_charge,if=rage<=40"

2022-03-24 22:48 UTC, nyterage submitted a review, later dismissed

2022-03-24 22:48 UTC, nyterage commented on engine/class_modules/sc_warrior.cpp
> +  default_list -> add_action( this, "Ignore Pain", "if=target.health.pct>=20&(target.health.pct>=80&!covenant.venthyr)&(rage>=85&cooldown.shield_slam.ready|rage>=60&cooldown.demoralizing_shout.ready&
```suggestion
  default_list -> add_action( this, "Ignore Pain", "if=target.health.pct>=20&(target.health.pct>=80&!covenant.venthyr)&(rage>=85&cooldown.shield_slam.ready|rage>=60&cooldown.demoralizing_shout.ready&talent.booming_voice.enabled|rage>=70&cooldown.avatar.ready|rage>=40&cooldown.demoralizing_shout.ready&talent.booming_voice.enabled&buff.last_stand.up|rage>=55&cooldown.avatar.ready&buff.last_stand.up|rage>=80|rage>=55&cooldown.shield_slam.ready&buff.outburst.up|rage>=30&cooldown.shield_slam.ready&buff.outburst.up&buff.last_stand.up),use_off_gcd=1");
```

2022-03-26 04:03 UTC, Armadk requested changes
I added a few gems in the sockets where they were missing, and updated all the bonus id's so they should be correct now.  Used all haste gems, in keeping with what had already been used.

2022-03-26 04:03 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +head=shadowghast_helm,id=171415,bonus_id=6647/6649/6716/8130/1588,gem_id=173128
```suggestion
head=shadowghast_helm,id=171415,bonus_id=6647/6649/6716/8130/1588/6935,gem_id=173128
```

6935 for items with a socket

2022-03-26 04:03 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +neck=cabochon_of_the_infinite_flight,id=185820,bonus_id=3536/4786/1808/1595
```suggestion
neck=cabochon_of_the_infinite_flight,id=185820,bonus_id=1595/6536/6646/6935,gem_id=173128
```
allowed to use a socket

2022-03-26 04:03 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +wrists=vambraces_of_the_infinite_infantry,id=188943,bonus_id=1505/7187,gem_id=173128
```suggestion
wrists=vambraces_of_the_infinite_infantry,id=188943,bonus_id=1505/7187/6935,gem_id=173128
```
6935 bonus id

2022-03-26 04:03 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +waist=girdle_of_the_soulflayer,id=179326,bonus_id=1592/7187
```suggestion
waist=girdle_of_the_soulflayer,id=179326,bonus_id=1592/6536/6646/6935,gem_id=173128
```
waist is allowed a gem

2022-03-26 04:03 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +finger1=bloodoath_signet,id=178871,bonus_id=3536/4786/1808/1592,gem_id=173128,enchant=tenet_of_haste
```suggestion
finger1=bloodoath_signet,id=178871,bonus_id=1592/6536/6646/6935,gem_id=173128,enchant=tenet_of_haste
```
socket, m+ id's

2022-03-26 04:03 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +finger2=arachnid_cipher_ring,id=178933,bonus_id=1592/7187,gem_id=173128,enchant=tenet_of_haste
```suggestion
finger2=arachnid_cipher_ring,id=178933,bonus_id=1592/6536/6646/6935,gem_id=173128,enchant=tenet_of_haste
```
socket + m+ bonusid

2022-03-26 04:03 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +trinket1=the_first_sigil,id=188271,bonus_id=1524
```suggestion
trinket1=the_first_sigil,id=188271,bonus_id=1524/7187
```

2022-03-26 04:03 UTC, Armadk commented on profiles/generators/Tier28/T28_Generate_Warrior.simc
> +trinket2=ticking_sack_of_terror,id=185844,bonus_id=1595/7187
```suggestion
trinket2=ticking_sack_of_terror,id=185844,bonus_id=1595/6536/6646
```

2022-03-27 05:13 UTC, Armadk approved these changes

2022-03-27 05:13 UTC, merged