[ele] fix lasso
simulationcraft/simc pull request #7089
Opened 2022-12-01 21:42 UTC by HawkCorrigan

2022-12-03 08:00 UTC, Bloodmallet requested changes

2022-12-03 08:00 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +  }
is this section necessary, if you set `affected_by_master_of_the_elements = true` above?

2022-12-03 08:00 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +  bool ready()override
please add a space between `()override`

2022-12-03 08:00 UTC, Bloodmallet commented on engine/class_modules/sc_shaman.cpp
> +  lightning_lasso_t( shaman_t* player, util::string_view options_str ) :
Could you remove your additional spaces?

2022-12-05 11:39 UTC, HawkCorrigan commented on engine/class_modules/sc_shaman.cpp
> +  }
yes

2022-12-05 12:43 UTC, merged