[Vengeance] add T30 2pc base implementation
simulationcraft/simc pull request #7428
Opened 2023-03-16 01:19 UTC by ToppleTheNun

2023-03-16 01:24 UTC, ToppleTheNun commented
@EvanMichaels

2023-03-19 03:09 UTC, EvanMichaels commented
Heya, do we not have spell data yet for this? Is it just not implemented in-game? Or do we need to whitelist some things for the generator?

2023-03-19 03:34 UTC, ToppleTheNun commented
VDH T30 isn't implemented in-game yet, I'm basing the implementation off of the announced tier bonus:
> (2) Set Bonus: Soul Fragments heal for 10% more and generating a Soul Fragment increases your Fire damage by 2% for 6 seconds. Multiple applications may overlap.
(4) Set Bonus: Shear and Fracture deal Fire damage. After consuming 20 Soul Fragments, your next cast of Shear or Fracture applies Fiery Brand to its target for 6 seconds.

2023-03-23 02:13 UTC, ToppleTheNun commented
@EvanMichaels Implemented using the actual spell data.

**Before**
![image](https://user-images.githubusercontent.com/1672786/227081574-29484b03-d0c6-4302-a701-2548776b83b7.png)

**After**
![image](https://user-images.githubusercontent.com/1672786/227081593-d52a4d01-6199-451d-aae6-206d11742e79.png)

2023-03-23 02:42 UTC, EvanMichaels requested changes

2023-03-23 02:42 UTC, EvanMichaels commented on engine/class_modules/sc_demon_hunter.cpp
> +    m *= 1.0 + buff.t30_vengeance_2pc->check() * set_bonuses.t30_vengeance_2pc_buff->effectN( 1 ).percent();
I think you probably could simplify to `m *= 1.0 + buff.t30_vengeance_2pc->stack_value()`? Think you are loading the effect into the default value of the buff via the ->set_default_value_from_effect( 1 )?

2023-03-23 02:42 UTC, EvanMichaels commented on engine/class_modules/sc_demon_hunter.cpp
> +  buff.t30_vengeance_2pc = make_buff<buff_t>(
Given the description "Multiple applications may overlap." is this a normal stacking buff or should this be `->set_stack_behavior( buff_stack_behavior::ASYNCHRONOUS )`? Usually they only use this wording for async behavior.

2023-03-23 02:42 UTC, EvanMichaels commented on engine/class_modules/sc_demon_hunter.cpp
> +  buff.t30_vengeance_4pc = make_buff<buff_t>(
As a note, the set bonus passive "#3 (id=1074773) : Apply Aura (6) | Modify Spell School (220)" should be able to be done with `apply_affecting_aura( set_bonuses.t30_vengeance_4pc )` in the normal passive application spot to do the school modification.

2023-03-25 17:46 UTC, merged