[Vengeance] add base T30 4pc implementation
simulationcraft/simc pull request #7471
Opened 2023-03-28 17:13 UTC by ToppleTheNun

T29 damage breakdown:
![image](https://user-images.githubusercontent.com/1672786/228316755-57e6a810-190c-4dd0-a7d9-49ce5c22bb88.png)

T30 damage breakdown:
![image](https://user-images.githubusercontent.com/1672786/228316785-459981f7-6817-4361-9364-71e78653689d.png)

2023-03-28 17:42 UTC, ToppleTheNun commented
@EvanMichaels

2023-03-29 03:25 UTC, EvanMichaels requested changes

2023-03-29 03:25 UTC, EvanMichaels commented on engine/class_modules/sc_demon_hunter.cpp
> +        p()->buff.t30_vengeance_4pc->reset();
->reset() is for end of iteration and resets some other things like last_start, last_trigger, etc. Should just use ->expire() here.

2023-03-29 03:25 UTC, EvanMichaels commented on engine/class_modules/sc_demon_hunter.cpp
> +      p()->buff.t30_vengeance_4pc->reset();
->reset() is for end of iteration and resets some other things like last_start, last_trigger, etc. Should just use ->expire() here.

2023-03-29 03:25 UTC, EvanMichaels commented on engine/class_modules/sc_demon_hunter.cpp
> +    double t30_vengeance_4pc_soul_fragments_tracker = 0;
You will need to add this to demon_hunter_t::reset() to set it back to 0 on iteration reset

2023-03-29 19:28 UTC, EvanMichaels approved these changes

2023-03-29 19:31 UTC, merged